services:
###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "5432:5432"
###< doctrine/doctrine-bundle ###

  ngrok:
    image: ngrok/ngrok
#    restart: unless-stopped
    ports:
      - "4040:4040"
    environment:
      NGROK_REGION: "eu"
      NGROK_AUTHTOKEN: ${NGROK_AUTH_TOKEN}
    command: ["http", "nginx:80", "--log=stdout"]
